services:
  gateway:
    build: ./service-node
    ports:
      - "8199:3000"
  app:
    build: ./service-python
    volumes:
      - vStorage:/vStorage
    networks:
      - default
  storage:
    build: ./service-storage
    volumes:
      - storageVolume:/storage
    networks:
      - default
volumes:
  vStorage:
  storageVolume: