services:
  gateway:
    build: ./service-node
    volumes:
      - ./vstorage:/vStorage
    ports:
      - "8199:3000"

  app:
    build: ./service-python
    volumes:
      - ./vstorage:/vStorage
    networks:
      - default

  storage:
    build: ./service-storage
    volumes:
      - storageVolume:/storage
    networks:
      - default

volumes:
  storageVolume: